version: 2
updates:
  - package-ecosystem: "gradle"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bobeal"
    open-pull-requests-limit: 10
    groups:
      detekt:
        patterns:
          - "io.gitlab.arturbosch.detekt*"
      kotlin:
        patterns:
          - "jvm"
          - "plugin.spring"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bobeal"
