repos:
- repo: local
  hooks:
  - id: detekt
    name: detekt check
    description: Runs `detekt` on modified .kt files.
    language: script
    entry: config/detekt/detekt_auto_correct.sh
    files: \.kt