# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
    jobs:
      post_checkout:
        # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
        #
        # Cancel building pull requests when there aren't changed in the docs directory.
        # 183 is a special exit code on Read the Docs that will cancel the build immediately.
        - |
          if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yml requirements/docs.txt;
          then
            echo "No changes to docs/ - exiting the build.";
            exit 183;
          fi
mkdocs:
  configuration: docs/mkdocs.yml

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
   - requirements: docs/files/requirements.txt
