spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/ngsi-ld/v1/**]':
                allowedOrigins: ${APPLICATION_CORS_ALLOWED_ORIGINS:http://localhost:3000}
                allowedMethods:
                  - GET
                  - POST
                  - PATCH
                  - PUT
                  - DELETE
                  - HEAD
                  - OPTIONS
                allowedHeaders: "*"

application:
  search-service:
    url: http://localhost:8083
  subscription-service:
    url: http://localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
    access:
      default: none
  endpoint:
    info:
      access: none
    health:
      access: read_only
  # Default values for sending observation data to an OpenTelemetry-capable backend
  # Log data is sent only if the 'otel' Spring profile is active
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

logbook:
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 200
  predicate:
    include:
      - path: /ngsi-ld/v1/**
