package com.egm.stellio.shared.model

val EXPANDED_ENTITY_SPECIFIC_MEMBERS = setOf(JSONLD_TYPE_KW, NGSILD_SCOPE_IRI)

val NGSILD_SYSATTRS_TERMS = setOf(NGSILD_CREATED_AT_TERM, NGSILD_MODIFIED_AT_TERM, NGSILD_DELETED_AT_TERM)

// List of members that are part of a core entity base definition (i.e., without attributes)
val EXPANDED_ENTITY_CORE_MEMBERS = setOf(
    JSONLD_ID_KW,
    JSONLD_TYPE_KW,
    JSONLD_CONTEXT_KW,
    NGSILD_SCOPE_IRI,
    NGSILD_CREATED_AT_IRI,
    NGSILD_MODIFIED_AT_IRI
)

val COMPACTED_ENTITY_CORE_MEMBERS = setOf(
    NGSILD_ID_TERM,
    NGSILD_TYPE_TERM,
    JSONLD_CONTEXT_KW,
    NGSILD_SCOPE_TERM,
    NGSILD_CREATED_AT_TERM,
    NGSILD_MODIFIED_AT_TERM
)

// Minimal terms that can be left in an entity after applying attributes projection
// In this case, the entity is considered to be empty and an error is returned
val COMPACTED_ENTITY_MINIMAL_MEMBERS = setOf(
    JSONLD_CONTEXT_KW,
    NGSILD_CREATED_AT_TERM,
    NGSILD_MODIFIED_AT_TERM
)

val COMPACTED_ATTRIBUTES_TERMS = setOf(
    NGSILD_VALUE_TERM,
    NGSILD_OBJECT_TERM,
    NGSILD_JSON_TERM,
    NGSILD_LANGUAGEMAP_TERM,
    NGSILD_VOCAB_TERM
)

val ATTRIBUTES_CORE_MEMBERS = setOf(
    JSONLD_TYPE_KW,
    NGSILD_CREATED_AT_IRI,
    NGSILD_MODIFIED_AT_IRI,
    NGSILD_OBSERVED_AT_IRI,
    NGSILD_DATASET_ID_IRI
)

val PROPERTIES_CORE_MEMBERS = setOf(
    NGSILD_PROPERTY_VALUE,
    NGSILD_UNIT_CODE_IRI
).plus(ATTRIBUTES_CORE_MEMBERS)

val PROPERTIES_FORBIDDEN_MEMBERS = setOf(
    NGSILD_RELATIONSHIP_OBJECT,
    NGSILD_JSONPROPERTY_JSON,
)

val RELATIONSHIPS_CORE_MEMBERS = setOf(
    NGSILD_RELATIONSHIP_OBJECT
).plus(ATTRIBUTES_CORE_MEMBERS)

val RELATIONSHIPS_FORBIDDEN_MEMBERS = setOf(
    NGSILD_PROPERTY_VALUE,
    NGSILD_JSONPROPERTY_JSON,
    NGSILD_UNIT_CODE_IRI
)

val GEOPROPERTIES_CORE_MEMBERS = setOf(
    NGSILD_GEOPROPERTY_VALUE
).plus(ATTRIBUTES_CORE_MEMBERS)

val GEOPROPERTIES_FORBIDDEN_MEMBERS = setOf(
    NGSILD_RELATIONSHIP_OBJECT,
    NGSILD_JSONPROPERTY_JSON,
    NGSILD_UNIT_CODE_IRI
)

val JSONPROPERTIES_CORE_MEMBERS = setOf(
    NGSILD_JSONPROPERTY_JSON
).plus(ATTRIBUTES_CORE_MEMBERS)

val JSONPROPERTIES_FORBIDDEN_MEMBERS = setOf(
    NGSILD_RELATIONSHIP_OBJECT,
    NGSILD_PROPERTY_VALUE,
    NGSILD_UNIT_CODE_IRI
)

val LANGUAGEPROPERTIES_CORE_MEMBERS = setOf(
    NGSILD_LANGUAGEPROPERTY_LANGUAGEMAP
).plus(ATTRIBUTES_CORE_MEMBERS)

val LANGUAGEPROPERTIES_FORBIDDEN_MEMBERS = setOf(
    NGSILD_RELATIONSHIP_OBJECT,
    NGSILD_PROPERTY_VALUE,
    NGSILD_UNIT_CODE_IRI
)

val VOCABPROPERTIES_CORE_MEMBERS = setOf(
    NGSILD_VOCABPROPERTY_VOCAB
).plus(ATTRIBUTES_CORE_MEMBERS)

val VOCABPROPERTIES_FORBIDDEN_MEMBERS = setOf(
    NGSILD_RELATIONSHIP_OBJECT,
    NGSILD_PROPERTY_VALUE,
    NGSILD_UNIT_CODE_IRI
)
