-- timestamps are generated by the app, no duplicates are possible
alter table attribute_instance_audit drop constraint if exists instance_audit_unicity;

-- an index on time column seems so silly...
drop index if exists attribute_instance_audit_observed_at_idx;

-- remove the foreign key on temporal_entity_attribute
-- checks are already done in the app and deletes are now handled in the code
alter table attribute_instance drop constraint if exists attribute_instance_temporal_entity_attribute_fkey;
alter table attribute_instance_audit drop constraint if exists attribute_instance_audit_temporal_entity_attribute_fkey;
