apiVersion: v1
kind: Service
metadata:
  labels:
    app: stellio-kafka
  name: stellio-kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    app: stellio-kafka
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stellio-kafka
  name: stellio-kafka
spec:
  selector:
    matchLabels:
      app: stellio-kafka
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: stellio-kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://stellio-kafka:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: INFO
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: confluentinc/cp-kafka:5.4.1
        name: stellio-kafka
        ports:
        - containerPort: 9092
          name: stellio-kafka
        resources: {}
      restartPolicy: Always
status: {}
