apiVersion: v1
kind: Service
metadata:
  labels:
    app: stellio-postgres
  name: stellio-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: stellio-postgres
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: stellio-postgres-storage
#   name: stellio-postgres-storage
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 30Gi
# status: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: stellio-postgres
  name: stellio-postgres
spec:
  selector:
    matchLabels:
      app: stellio-postgres
  serviceName: stellio-postgres
  replicas: 1
  # strategy: # only for Deployment
  #   type: Recreate
  template:
    metadata:
      labels:
        app: stellio-postgres
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector: {}
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: STELLIO_SEARCH_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: STELLIO_SEARCH_DB_DATABASE
        - name: POSTGRES_DBNAME
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: POSTGRES_DBNAME
        - name: STELLIO_SUBSCRIPTION_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: STELLIO_SUBSCRIPTION_DB_DATABASE
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: POSTGRES_USER
        - name: POSTGRES_PASS
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: POSTGRES_PASS
        - name: ACCEPT_TIMESCALE_TUNING
          value: "TRUE"
        - name: POSTGRES_MULTIPLE_EXTENSIONS
          value: postgis,timescaledb,pgcrypto
        image: stellio/stellio-timescale-postgis:14-2.11.1-3.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
        # "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -d "dbname=stellio_search" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - -e
        #     - |
        #       exec pg_isready -U "postgres" -d "dbname=stellio_search" -h 127.0.0.1 -p 5432
        #       [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
        #   failureThreshold: 6
        #   initialDelaySeconds: 5
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 5
        name: stellio-postgres
        ports:
        - containerPort: 5432
          name: postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: stellio-postgres-storage
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: stellio-postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: ${STORAGE_CLASS}
        resources:
          requests:
            storage: 80Gi
