name: Anchore Security Scan for Node Slim
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  anchore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build local container
        uses: docker/build-push-action@v2
        with:
          path: ./search-service/docker
          tags: localbuild/search-service:latest-scan
          push: false
          load: true
      - name: Security Scan for search-service image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/search-service:latest-scan"
          acs-report-enable: true
          severity-cutoff: critical
      - name: Upload security scan report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: security-scan-report
          path: ${{ steps.scan-base.outputs.sarif }}
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: ${{ steps.scan-base.outputs.sarif }}
