name: Commit Check

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:  # use permissions because use of pr-comments
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0  # Required for merge-base checks
      - uses: commit-check/commit-check-action@108aca470d4737070cc5416d7cfe82f64e23513d # V2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR comments
        with:
          message: true
          branch: true
          author-name: false
          author-email: false
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}
