name: Commit Check

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:  # use permissions because use of pr-comments
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0  # Required for merge-base checks
      - uses: commit-check/commit-check-action@7c158d4541309c5952de3343151750882b036d10 # V2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR comments
        with:
          message: true
          branch: true
          author-name: false
          author-email: false
          job-summary: true
          pr-comments: ${{ github.event_name == 'pull_request' }}
